version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["node_modules/http-proxy/lib/"]

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor",
    "angularjs",
    "angular"
  ]